set_property SRC_FILE_INFO {cfile:d:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.srcs/sources_1/ip/twentyFive_mhz_clk/twentyFive_mhz_clk.xdc rfile:../../../StopWatch_1.srcs/sources_1/ip/twentyFive_mhz_clk/twentyFive_mhz_clk.xdc id:1 order:EARLY scoped_inst:clk_div/clkwiz/inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.srcs/constrs_1/new/pmod_test.xdc rfile:../../../StopWatch_1.srcs/constrs_1/new/pmod_test.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.10000000000000001
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports enc_a]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports enc_b]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports enc_btn]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports enc_sw]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB7 [get_ports enc_a]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB6 [get_ports enc_b]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y4 [get_ports enc_btn]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA4 [get_ports enc_sw]
