# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/new_stuff_30_3_19/StopWatch_1/PMOD_segment/PMOD_segment.cache/wt [current_project]
set_property parent.project_path D:/new_stuff_30_3_19/StopWatch_1/PMOD_segment/PMOD_segment.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo d:/new_stuff_30_3_19/StopWatch_1/PMOD_segment/PMOD_segment.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/new_stuff_30_3_19/StopWatch_1/PMOD_segment/PMOD_segment.srcs/sources_1/new/debounce.v
  D:/new_stuff_30_3_19/StopWatch_1/PMOD_segment/PMOD_segment.srcs/sources_1/new/ssd.v
  D:/new_stuff_30_3_19/StopWatch_1/PMOD_segment/PMOD_segment.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/new_stuff_30_3_19/StopWatch_1/PMOD_segment/PMOD_segment.srcs/constrs_1/new/PMODconst.xdc
set_property used_in_implementation false [get_files D:/new_stuff_30_3_19/StopWatch_1/PMOD_segment/PMOD_segment.srcs/constrs_1/new/PMODconst.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
