# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pmod_test.xdc

# IP: ip/twentyFive_mhz_clk/twentyFive_mhz_clk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==twentyFive_mhz_clk || ORIG_REF_NAME==twentyFive_mhz_clk}]

# XDC: ip/twentyFive_mhz_clk/twentyFive_mhz_clk_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==twentyFive_mhz_clk || ORIG_REF_NAME==twentyFive_mhz_clk}] {/inst }]/inst ]]

# XDC: ip/twentyFive_mhz_clk/twentyFive_mhz_clk.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==twentyFive_mhz_clk || ORIG_REF_NAME==twentyFive_mhz_clk}] {/inst }]/inst ]]

# XDC: ip/twentyFive_mhz_clk/twentyFive_mhz_clk_ooc.xdc
