# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.cache/wt [current_project]
set_property parent.project_path D:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_repo_paths d:/lab_sources [current_project]
set_property ip_output_repo d:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.srcs/sources_1/new/up_down_counter.v
  D:/new_stuff_30_3_19/StopWatch_1/clk_divider.v
  D:/new_stuff_30_3_19/StopWatch_1/BCD_Decoder.v
  D:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.srcs/sources_1/new/Master_Controller.v
}
read_ip -quiet D:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.srcs/sources_1/ip/twentyFive_mhz_clk/twentyFive_mhz_clk.xci
set_property used_in_implementation false [get_files -all d:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.srcs/sources_1/ip/twentyFive_mhz_clk/twentyFive_mhz_clk_board.xdc]
set_property used_in_implementation false [get_files -all d:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.srcs/sources_1/ip/twentyFive_mhz_clk/twentyFive_mhz_clk.xdc]
set_property used_in_implementation false [get_files -all d:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.srcs/sources_1/ip/twentyFive_mhz_clk/twentyFive_mhz_clk_ooc.xdc]
set_property is_locked true [get_files D:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.srcs/sources_1/ip/twentyFive_mhz_clk/twentyFive_mhz_clk.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.srcs/constrs_1/new/pmod_test.xdc
set_property used_in_implementation false [get_files D:/new_stuff_30_3_19/StopWatch_1/StopWatch_1/StopWatch_1.srcs/constrs_1/new/pmod_test.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Master_Controller -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Master_Controller.dcp

catch { report_utilization -file Master_Controller_utilization_synth.rpt -pb Master_Controller_utilization_synth.pb }
